steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "gcr.io/projectdenimar01/github-denimar-server-test:$TAG_NAME", "."]
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/projectdenimar01/github-denimar-server-test:$TAG_NAME"]
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment'
  - 'microservice01'
  - 'microservice01=gcr.io/projectdenimar01/github-denimar-server-test:$TAG_NAME'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=projects-cluster'
  - 'GOOGLE_APPLICATION_CREDENTIALS=projectdenimar01-5472b2034a4b.json'