version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.3 
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
  test:
    docker:
      - image: circleci/node:8.11.3     
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install      
      - run: npm test
  tagging:
    docker:
      - image: circleci/node:8.11.3     
    working_directory: ~/repo
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "56:a9:7f:5a:8e:99:38:4c:52:42:df:84:e8:4d:fe:16"
      - run: npm run tagging
workflows:
  version: 2
  build_test_and_tagging:
    jobs:
      - build
      - test:
          requires:
            - build
      - tagging:
          requires:
            - test            