version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.3 
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
  test:
    docker:
      - image: circleci/node:8.11.3     
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install      
      - run: npm test
  tagging:
    docker:
      - image: circleci/node:8.11.3     
    working_directory: ~/repo
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "92:15:79:33:11:13:55:cb:bc:4c:0b:2f:7c:16:a4:7b"
      - run: npm run tagging
workflows:
  version: 2
  build_test_and_tagging:
    jobs:
      - build
      - test:
          requires:
            - build
      - request-tagging:
          type: approval
          requires:
            - test
      - tagging:
          requires:
            - request-tagging            