version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.3 
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
  test:
    docker:
      - image: circleci/node:8.11.3     
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install      
      - run: npm test
  tagging:
    docker:
      - image: circleci/node:8.11.3     
    working_directory: ~/repo
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "73cafcf7d0773ab4dcb02f445d734c2159e35cb1"      
      - run: npm run tagging
workflows:
  version: 2
  build_test_and_tagging:
    jobs:
      - build
      - test:
          requires:
            - build
      - tagging:
          requires:
            - test            