version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.3 
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
  test:
    docker:
      - image: circleci/node:8.11.3     
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install      
      - run: npm test
  tagging:
    docker:
      - image: circleci/node:8.11.3     
    working_directory: ~/repo
    steps:
      environment:
        - GH_TOKEN: 0b920b8b68def28018b8e9cad728d60f197b35e6      
      - checkout
      - run: npm run tagging
workflows:
  version: 2
  build_test_and_tagging:
    jobs:
      - build
      - test:
          requires:
            - build
      - tagging:
          requires:
            - test            